
Page({
  data:{
    Mone:true,
    text:"亲爱的，你今天的幸运数字是多少呀？",
  },
  a(){
    this.setData({
      Mone:false,
      text:"好呀好呀，来，把眼睛闭上！",
      Mtwo:true,
      Atwo:true,
    })
  },
  b(){
    this.setData({
      Mone:false,
      text:"你可以滚了",
    })
  },
  c(){
    this.setData({
      Mtwo:false,
      Atwo:false,
      text:"你是不是不耐烦了？不想玩就早说！玩你的手机去吧！",
    })
  },
  d(){
    this.setData({
      Mtwo:false,
      Atwo:false,
      text:"真乖！奖励一个么么哒————来，抽张卡！",
      Mthree:true,
      Athree:true,
    })
  },
  e(){
    this.setData({
      Mthree:false,
      Athree:false,
      text:"哎哎哎，你干嘛呢？",
      Mfour:true,
    })
  },
  f(){
    this.setData({
      Mthree:false,
      Athree:false,
      text:"你安安稳稳地度过了女朋友这次的突发奇想",
    })
  },
  g(){
    this.setData({
      Mfour:false,
      text:"你的女朋友非常开心，你们的感情更进一步",
    })
  },
});